export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
[ -f ~/.zplugrc ] && source ~/.zplugrc

# load aliases
[[ -f ~/.aliases ]] && source ~/.aliases
