#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# Install fonts
git -C fonts pull || git clone git@github.com:alexfridlyand/personal-fonts.git fonts
mkdir -p ~/.local/share/fonts
cp -r fonts/* ~/.local/share/fonts/

sudo apt install -y \
        brightnessctl brightness-udev \
		emacs \
		i3 \
		pulsemixer \
		suckless-tools \
	    corebird \
        curl \
        htop \
        mosh \
		numlockx \
        rxvt-unicode-256color \
		scrot \
        tmux \
        wmctrl \
        xcape \

# Install fish
sudo apt install -y fish
grep -q -F "/usr/bin/fish" "/etc/shells" || echo "/usr/bin/fish" | sudo tee -a "/etc/shells"
chsh -s /usr/bin/fish
printf "$(curl -L https://get.oh-my.fish)\nexit" > omf/install
fish omf/install -y --noninteractive
rm -rf omf/install

# Install emacs config
git -C ~/.emacs.d pull || git clone -b develop git@github.com:syl20bnr/spacemacs.git ~/.emacs.d

# Install snaps
sudo apt install snapd
sudo snap login

snap install skype --classic
snap install slack --classic
snap install mailspring
